feat(partner): Adds REWE
nightlybuild-conference/nightlybuild-io-2017 pull request #17
Opened 2017-07-12 10:04 UTC by asciidisco

2017-07-12 10:05 UTC, asciidisco commented
Please merge after the contract is signed & ready.

2017-07-12 10:45 UTC, drublic commented
@asciidisco Die müssen noch in den Header und den Footer, oder?

2017-07-12 11:03 UTC, asciidisco commented
@drublic Ah, correct, good catch. I´ll adapt the PR.

2017-07-25 05:31 UTC, anselmh requested changes

2017-07-25 05:31 UTC, anselmh commented on lib/views/layouts/default.html
>                                  <img class="image" src="img/sponsors/trivago-logo.svg">
Hm, hier stimmt die ID im Link nicht in der Ziel darüber.

2017-07-25 05:31 UTC, anselmh commented on lib/views/layouts/default.html
> +                        <a href="/partner#trivago">
s.o.

2017-08-15 11:46 UTC, merged